export const problemi = [
  "Filtra numeri dispari da un array e moltiplica per 2",
  "Somma tutti gli elementi di un array",
  "Trova il numero massimo in un array",
  "Conta quante volte appare una parola in una stringa",
  "Inverti una stringa",
  "Controlla se una parola è palindroma",
  "Calcola la somma dei primi N numeri naturali",
  "Trova il minimo comune multiplo di due numeri",
  "Somma solo i numeri positivi in un array",
  "Rimuovi duplicati da un array",
  "Trasforma tutti gli elementi di un array in stringhe",
  "Conta quante parole ci sono in una frase",
  "Filtra numeri maggiori di una soglia",
  "Trova la media di un array di numeri",
  "Unisci due array e ordina i valori",
  "Controlla se un numero è primo",
  "Trova l’indice di un elemento in un array",
  "Calcola il fattoriale di un numero",
  "Trova elementi comuni tra due array",
  "Somma elementi pari di un array",
  "Genera una sequenza Fibonacci fino a N",
  "Sostituisci una parola in una frase",
  "Conta quante vocali ci sono in una stringa",
  "Controlla se un array è ordinato",
  "Trova il secondo numero più grande in un array",
  "Rimuovi spazi extra da una stringa",
  "Calcola la potenza di un numero senza Math.pow",
  "Trova la lunghezza della parola più lunga in una frase",
  "Inverte l’ordine degli elementi in un array",
  "Somma tutti i numeri in un oggetto (chiave: valore numerico)",
  "Filtra array di oggetti per una proprietà",
  "Ordina array di numeri in ordine decrescente",
  "Controlla se due stringhe sono anagrammi",
  "Trova il numero più frequente in un array",
  "Conta quante parole iniziano con una lettera specifica",
  "Genera una tabella di moltiplicazione fino a N",
  "Trova gli elementi unici tra due array",
  "Sostituisci caratteri speciali in una stringa",
  "Trova tutti i numeri divisibili per 3 in un array",
  "Calcola il prodotto di tutti gli elementi di un array",
  "Conta quanti elementi true ci sono in un array di booleani",
  "Trova l’elemento più vicino a un numero dato",
  "Raggruppa array di numeri in pari e dispari",
  "Trasforma tutte le stringhe in minuscolo",
  "Somma solo numeri multipli di 5",
  "Controlla se una parola contiene solo lettere",
  "Trova il numero più piccolo in un array di oggetti",
  "Rimuovi tutti i numeri negativi da un array",
  "Trova elementi presenti solo in un array e non nell’altro",
  "Crea un oggetto da due array (chiavi e valori)",
  "Controlla se una stringa inizia con un prefisso dato",
  "Conta quante volte appare un numero in un array",
  "Genera un array di numeri casuali tra min e max",
  "Calcola la somma diagonale di una matrice 2D",
  "Trova il numero più grande per ogni riga di una matrice",
  "Trasponi una matrice 2D",
  "Filtra array di stringhe lunghe più di N",
  "Somma gli elementi di array di array (2D)",
  "Trova tutte le parole duplicate in una frase",
  "Rimuovi tutte le lettere maiuscole da una stringa",
  "Trova elementi divisibili sia per 2 che per 3",
  "Inverti ordine delle parole in una frase",
  "Trova l’elemento più vicino alla media di un array",
  "Raggruppa parole per lunghezza",
  "Somma valori di un array con reduce (JS)",
  "Calcola media ponderata da array di oggetti",
  "Conta numeri dispari in matrice 2D",
  "Trova il carattere più frequente in una stringa",
  "Ordina array di oggetti per una proprietà",
  "Rimuovi valori falsy da un array",
  "Trova tutti i numeri primi fino a N",
  "Controlla se una matrice è simmetrica",
  "Trasforma array di numeri in stringhe con un pattern",
  "Rimuovi elementi null/undefined da array",
  "Genera sequenza di numeri pari fino a N",
  "Conta quante parole hanno lunghezza pari",
  "Somma numeri in stringa (es: \"1,2,3\" → 6)",
  "Trova elementi duplicati tra più array",
  "Concatena stringhe alternate da due array",
  "Filtra numeri tra due valori min/max",
  "Trova la differenza tra due array",
  "Trova elementi maggiori del precedente in array",
  "Controlla se array contiene solo numeri",
  "Somma valori di oggetto annidato",
  "Raggruppa numeri per modulo (divisibilità)",
  "Trova elementi comuni in più array",
  "Rimuovi caratteri non alfabetici",
  "Controlla se stringa è palindroma ignorando spazi",
  "Ordina parole in ordine alfabetico",
  "Genera array di numeri casuali unici tra min/max"
]